# Generated by Django 5.1.4 on 2024-12-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_news_image_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, upload_to='news_videos/', verbose_name='ویدئو خبر'),
        ),
    ]
