# Generated by Django 5.1.4 on 2024-12-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
