# Generated by Django 5.1.4 on 2025-01-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, to='news.category', verbose_name='Category'),
        ),
    ]
