# Generated by Django 5.1.4 on 2025-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_category_news_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
