# Generated by Django 4.2.17 on 2026-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_likes_alter_news_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_date'], name='news_published_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-views_count'], name='news_views_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status'], name='news_status_idx'),
        ),
    ]
