# Generated by Django 4.2.17 on 2026-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_category_slug_news_slug_news_news_slug_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
