# Generated by Django 4.2.17 on 2026-08-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_fulltext_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_inline/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_images', to='news.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'Inline image',
                'verbose_name_plural': 'Inline images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
