# Generated by Django 4.2.17 on 2026-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newsinlineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Translations'),
        ),
    ]
