# Generated by Django 5.1.4 on 2024-12-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
