# Generated by Django 5.1.4 on 2025-01-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'کاربر عادی'), ('admin', 'ادمین'), ('super_admin', 'کاربر ارشد')], default='normal', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
