# Generated by Django 5.1.4 on 2025-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=225, verbose_name='نام سایت'),
        ),
    ]
