# Generated by Django 5.1.4 on 2025-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sitesettings_default_email_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, verbose_name='شماره تماس'),
        ),
    ]
