# Generated by Django 5.1.4 on 2025-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitesettings_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='normal', max_length=20, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Default Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Footer Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=225, verbose_name='Site Name'),
        ),
    ]
